---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

<p id = "title">Used 114 Colorado mountain <a id="link" href="https://byuidatascience.github.io/WolfeA_SeniorProject/station_map.html" target = "_blank"> SNOTEL stations.</a></p>

<br><br>

```{r, message = FALSE, warning = FALSE, echo = FALSE}
# get data
snow <- read_csv("../../../data/full_snow.csv")

# Code in elevations, order them
snow.1 <- snow %>% 
  mutate(elev_level = case_when(
    elev > 8000 & elev < 9000 ~ "8K-9K",
    elev > 9000 & elev < 10000 ~ "9K-10K",
    elev > 10000 & elev < 11000 ~ "10K-11K",
    elev > 11000 & elev < 12000 ~ "11K-12K"),
    elev_level = fct_relevel(elev_level, 
                             levels = c("8K-9K", 
                                        "9K-10K", 
                                        "10K-11K",
                                        "11K-12K")))

# yearly max temp
high_plot <- snow.1 %>% 
  filter(year != 2018) %>% 
  group_by(elev_level, year) %>% 
  summarise(high_temp = mean(max_temp_mean),
            low_temp = mean(min_temp_mean)) %>% 
  ggplot(aes(x = year, y = high_temp, color = elev_level)) +
  geom_line(size = 2) +
  theme_bw() +
  labs(x = "Year",
       y = "High Temp",
       color = "Elevation",
       title = "Yearly Max Temp per Elevation") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5)))

# yearly low temp
low_plot <- snow.1 %>% 
  filter(year != 2018) %>% 
  group_by(elev_level, year) %>% 
  summarise(high_temp = mean(max_temp_mean),
            low_temp = mean(min_temp_mean)) %>% 
  ggplot(aes(x = year, y = low_temp, color = elev_level)) +
  geom_line(size = 2) +
  geom_smooth(method = "lm", color = "black", se = FALSE, size = 2) +
  theme_bw() +
  labs(x = "Year",
       y = "High Temp",
       color = "Elevation",
       title = "Yearly Low Temp per Elevation") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5)))

# yearly high-low temp scale
scale_plot <- snow.1 %>% 
  filter(year != 2018) %>% 
  group_by(elev_level, year) %>% 
  summarize(mean_t = mean(max_temp_mean),
            mean_l = mean(min_temp_mean)) %>% 
  mutate(scale_temp = round(mean_t/mean_l, 3)) %>%
  ggplot(aes(x = year, y = scale_temp, color = elev_level)) +
  geom_line(size = 2) +
  theme_bw() +
  labs(x = "Year",
       y = "High/Low",
       color = "Elevation",
       title = "Yearly Mean High/Low Proportion",
       caption = "Nights are getting warmer, and daily temp variation smaller") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5)),
        plot.caption = element_text(face = "bold", size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5)))

# May Snow Depth
may_plot <- snow.1 %>% 
  filter(mon == "May",
         start_snow_depth > 0) %>% 
  group_by(year, elev_level) %>% 
  summarise(may_snow = mean(start_snow_depth)) %>% 
  ggplot(aes(x = year, y = may_snow, color = elev_level)) +
  geom_line(size = 2) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(x = "Year",
       y = "Snow Depth",
       color = "Elevation",
       title = "Yearly May Snow Depth per Elevation") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5))) +
  scale_color_manual(values = c("#885C0E",
                                "#12A21B",
                                "#9E1D10",
                                "#091661"))

# June Snow Depth
jun_plot <- snow.1 %>% 
  filter(mon == "Jun",
         start_snow_depth > 0,
         elev_level != "8K-9K") %>% 
  group_by(year, elev_level) %>% 
  summarise(june_snow = mean(start_snow_depth)) %>% 
  ggplot(aes(x = year, y = june_snow, color = elev_level)) +
  geom_line(size = 2) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(x = "Year",
       y = "Snow Depth",
       color = "Elevation",
       title = "Yearly June Snow Depth per Elevation") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5))) +
  scale_color_manual(values = c("#12A21B",
                                "#9E1D10",
                                "#091661"))


# Nov Snow Depth
nov_plot <- snow.1 %>% 
  filter(mon == "Nov",
         start_snow_depth > 0) %>% 
  group_by(year, elev_level) %>% 
  summarise(nov_snow = mean(start_snow_depth)) %>% 
  ggplot(aes(x = year, y = nov_snow, color = elev_level)) +
  geom_line(size = 2) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(x = "Year",
       y = "Snow Depth",
       color = "Elevation",
       title = "Yearly November Snow Depth per Elevation") +
  theme(plot.title = element_text(size = rel(2), face = "bold", hjust = .5),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.5)),
        legend.title = element_text(size = rel(1.5))) +
  scale_x_continuous(breaks = seq(1975, 2020, 2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = .3),
        legend.text = element_text(size = rel(1.5))) +
  scale_color_manual(values = c("#885C0E",
                                "#12A21B",
                                "#9E1D10",
                                "#091661"))
```

```{r, message = FALSE, warning = FALSE, echo = FALSE, fig.height=34, fig.width=13}
# arranged
ggarrange(high_plot, low_plot, scale_plot, may_plot, jun_plot, nov_plot, nrow = 6)
```

<style>
@import url('https://fonts.googleapis.com/css?family=Rasa');
#title{
text-align: center;
margin: auto;
font-size: 50px;
color: #729BE9;
font-family: 'Rasa', serif;
}
#link{
text-align: center;
margin: auto;
font-size: 50px;
color: #1DA11F;
font-family: 'Rasa', serif;
}
</style>