---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, leaflet, lubridate, ggpubr, DT)
theme_set(theme_bw())
```

<p id = "title"><strong>Working With Temperature</strong></p>

<br><br>

<p id = "desc">After collecting the data, I went through a process of visualizing the data, finding a model of re-estimation, imputing problematic values, and analyzing the outcome.<br><br>The following are links that highlight each step of the process.<br><br></p>

<ul id = "bullet">
  <li id = "list"><a id = "link" href = "https://byuidatascience.github.io/WolfeA_SeniorProject/temp_check.html" target = "_blank">Checking Data</a></li>
  <li id = "list"><a id = "link" href = "https://byuidatascience.github.io/WolfeA_SeniorProject/temp_estimation.html" target = "_blank">Imputing Values</a></li>
  <li id = "list"><a id = "link" href = "https://byuidatascience.github.io/WolfeA_SeniorProject/temp_validation.html" target = "_blank">Model Validation</a></li>
  <li id = "list"><a id = "link" href = "https://byuidatascience.github.io/WolfeA_SeniorProject/temp_visualize.html" target = "_blank">Visualizations</a></li>
</ul>


<br><br>
<p id = "desc"> </p>
<a id = "link" href = "" target = "_blank"> </a>
<i></i>
<strong></strong>



<style>
@import url('https://fonts.googleapis.com/css?family=Oswald|Ubuntu');
@import url('https://fonts.googleapis.com/css?family=Quicksand');
#title {
margin: auto;
text-align: center;
font-size: 70px;
font-family: 'Ubuntu', sans-serif;
}
#desc{
font-size: 30px;
font-family: 'Quicksand', sans-serif;
}
#link{
font-size: 35px;
font-family: 'Quicksand', sans-serif;
margin-bottom: .5em;
}
#bullet{
list-style-type: square;
}
#list{
font-size: 20px;
font-family: 'Quicksand', sans-serif;
margin-bottom: .5em;
}
#section{
margin: auto;
text-align: center;
font-size: 45px;
font-family: 'Yanone Kaffeesatz', sans-serif;
color: #106414;
letter-spacing: 5px;
}
</style>



